pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
	sh 'mvn -f multi-stage-multi-agent/pom.xml -X clean install'
      }
    }
    stage('Install dependencies') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
	script {
		// Install npm packages
        	sh 'npm install'
      		}
    	}
    }
    stage('Run Hello World') {
      steps {
	script {
		// Run the Node.js app
		sh 'npm start & sleep 5' // Start app in background for demo
		sh 'curl -s http://localhost:3000' // Test endpoint
		}
	}
    }
  }
}
